### ISSUE TITLE
error

### ISSUE THREAD

**Issue by axin0452** [SettingDust/DustSponge#7]
`[18:47:34] [Server thread/ERROR] [Sponge]: Could not pass DropItemEvent$Destruct$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=4.3.0, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=.\mods\[c][领地插件]griefprevention-1.12.2-4.3.0.662.jar}
java.lang.ClassCastException: org.spongepowered.common.item.inventory.SpongeItemStackSnapshot cannot be cast to org.spongepowered.api.entity.Entity
        at me.ryanhamshire.griefprevention.listener.EntityEventHandler.onEntitySpawn(EntityEventHandler.java:183) ~[EntityEventHandler.class:1.12.2-4.3.0.662]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_EntityEventHandler_onEntitySpawn190.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.5]
        at com.settingdust.dustdeathpenalty.module.main.handler.DropHandler.spawnItems(DropHandler.java:230) [DropHandler.class:?]
        at com.settingdust.dustdeathpenalty.module.main.handler.DropHandler.dropItemAndExp(DropHandler.java:68) [DropHandler.class:?]
        at org.spongepowered.common.event.listener.DeathListener_DropHandler_dropItemAndExp201.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) [SpongeImpl.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:943) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:3849) [oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3637) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) [oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1318) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1946) [aed.class:?]
        at net.minecraft.block.Block.func_180658_a(Block.java:821) [aow.class:?]
        at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$zed000(Entity.java:6043) [vg.class:?]
        at net.minecraft.entity.Entity.func_184231_a(Entity.java:1132) [vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:215) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:838) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:585) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) [lk$b.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[18:47:34] [Server thread/ERROR] [Sponge]: Could not pass DropItemEvent$Destruct$Impl to Plugin{id=nucleus, name=Nucleus, version=1.6.1-S7.1, description=The Ultimate Essentials Plugin., url=http://nucleuspowered.org, source=.\mods\[c][基础插件]Nucleus-1.6.1-S7.1-MC1.12.2-plugin.jar}
java.lang.ClassCastException: org.spongepowered.common.item.inventory.SpongeItemStackSnapshot cannot be cast to org.spongepowered.api.entity.Entity
        at org.spongepowered.api.event.entity.AffectEntityEvent.filterEntities(AffectEntityEvent.java:118) ~[AffectEntityEvent.class:1.12.2-2768-7.1.5]
        at io.github.nucleuspowered.nucleus.modules.mob.listeners.BlockLivingSpawnListener.onSpawn(BlockLivingSpawnListener.java:47) ~[BlockLivingSpawnListener.class:1.6.1-S7.1]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_BlockLivingSpawnListener_onSpawn71.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.5]
        at com.settingdust.dustdeathpenalty.module.main.handler.DropHandler.spawnItems(DropHandler.java:230) [DropHandler.class:?]
        at com.settingdust.dustdeathpenalty.module.main.handler.DropHandler.dropItemAndExp(DropHandler.java:68) [DropHandler.class:?]
        at org.spongepowered.common.event.listener.DeathListener_DropHandler_dropItemAndExp201.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) [SpongeImpl.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:943) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.5]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:3849) [oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3637) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) [oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1318) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1946) [aed.class:?]
        at net.minecraft.block.Block.func_180658_a(Block.java:821) [aow.class:?]
        at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$zed000(Entity.java:6043) [vg.class:?]
        at net.minecraft.entity.Entity.func_184231_a(Entity.java:1132) [vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:215) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:838) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:585) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) [lk$b.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

forge-1.12.2-14.23.5.2775-universal.jar
![image](https://user-images.githubusercontent.com/39695561/63636292-f5f3b500-c69f-11e9-84d8-b9da70622762.png)

**Comment by SettingDust** [comment]
Its not my plugin.
